### ISSUE TITLE
FacebookProvider breaks RememberMe filter

### ISSUE THREAD

**Issue by wujashek** [FriendsOfSymfony/FOSFacebookBundle#26] opened 2011-04-21 08:37 UTC
RememeberMe has two user providers (from UserBundle and FacebookBundle), it takes first so FacebookProvider is used and user is never found by is username.  I've just added

Maybe I'm doing something wrong in configuration.

Not elegant way to deal with it:

```
public function loadUserByUsername($username)
{
    // try to load by username
    // dirty hack for remember me filter which uses same provider
    $user = $this->userManager->findUserBy(array('username' => $username));
```

**Comment by schmittjoh** [comment] 2011-04-21 09:59
Do you use the same user class for both providers?

**Comment by wujashek** [comment] 2011-04-21 10:36
Yes, because both providers creates same entity class...

**Comment by ornicar** [comment] 2011-04-21 16:10
Yep I also ran into this issue yesterday. I quickfixed it by letting the facebook provider load fos users... better idea anyone?

**Comment by wujashek** [comment] 2011-04-22 08:41
No real solutions without changing the way security component works, imo quickfix should be included in facebook bundle documentation...

**Comment by schmittjoh** [comment] 2011-04-22 08:42
I think it makes sense to have different user classes for Facebook, and your
normal users.

**Comment by wujashek** [comment] 2011-04-22 08:52
There's only normal users. I'm talking about facebook provider which produces the user entity (example in this bundle docs).  remember_me filter should have provider argument or take provider from firewall which has remember_me set to true.

**Comment by lsmith77** [comment] 2011-05-21 12:44
We have something along these lines running fine in production:
https://github.com/liip/HelloBundle/blob/master/Security/User/Provider/FacebookProvider.php

**Comment by schmittjoh** [comment] 2011-07-17 06:35
You can now also define which providers remember-me should try. Closing this.

**Closed as completed by schmittjoh** 2011-07-17 06:35 UTC

**Comment by Tanariel** [comment] 2012-07-16 12:17
Sorry to jump on a so old issue but i'm facing the problem actually and i don't understand how to solve it.

I'm currently using FOSUserBundle + FOSFacebookBundle + FOSTwitterBundle.

Everything works fine for the authentication of each module but the REMEMBERME function is broken.

My User entity has a property username and a property FacebookId. 

The problem is In fact that Symfony try to authenticate the user against the facebook user provider and of course the following code can't return a correct answer as the query try to find a facebookId with a username : 

<pre>
<code>
public function findUserByFbId($fbId)
    {
        return $this->userManager->findUserBy(array('facebookId' => $fbId));
    }

    public function loadUserByUsername($username)
    {
        $user = $this->findUserByFbId($username);
        //some code here
    }
</code>
</pre>


The last comment speak about the fact that you can define wich provider the remember_me should try, but i didn't find this option. In the security config reference of symfony2 the only option that can be stated in the remember_me section is "token_provider: name" , but if i try to put a user provider there i got an exception assuming it's not a token provider but a user provider i'm providing.

<pre>
<code>
Catchable Fatal Error: Argument 1 passed to Symfony\Component\Security\Http\RememberMe\PersistentTokenBasedRememberMeServices::setTokenProvider() must be an instance of Symfony\Component\Security\Core\Authentication\RememberMe\TokenProviderInterface, instance of Acme\UserBundle\Security\Provider\UserProvider given, called in /home/Acme/Symfony/app/cache/dev/appDevDebugProjectContainer.php on line 1888 and defined in /home/Acme/Symfony/vendor/symfony/src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php line 41
</code>
</pre>


i may have missed what <b>schmittjoh</b> meant by : "You can now also define which providers remember-me should try. Closing this.", where can be defined wich provider the remember-me function should try ?

<u>Note :</u> In my security.yml i use this : 

<pre>
<code>
providers:
        chain_provider:
            providers: [user, fb_provider, fos_twitter ]
        user:
            id: my.user_provider
        fb_provider:
            id: my.facebook.user
        fos_twitter:
            id: my.twitter.user
</code>
</pre>

so shouldn't symfony try to authenticate the remembered user vs the user provider instead of trying to authenticate it vs the facebook provider ?

**Comment by scheb** [comment] 2012-08-22 10:24
Had the same problem and it took me some time to find the solution in the code, because there is no documentation for this option:

```
remember_me:
    user_providers: [ user_provider_name ]
```
